[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# RPC endpoints
[rpc_endpoints]
sepolia = "https://sepolia.gateway.tenderly.co"
base = "https://mainnet.base.org"
coredao = "https://rpc.coredao.org"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
